name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Get .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.*'
    
    - name: dotnet publish
      run: |
        cd src/apireview.net 
        dotnet publish -c Release --self-contained -r linux-x64 /p:SourceRevisionId=${{ github.sha }}  -o '../../artifacts/ApiReviewDotNet'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: apireview
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: './artifacts/ApiReviewDotNet'
